use clap::Parser;

#[derive(Debug, Parser)]
#[command(about, version)]
pub struct Cli {
    #[arg(help = "Content to be hashed")]
    pub content: String,

    #[arg(short, long, help = "Hashing algorithm (case insensitive)\n - Options: Argon2i, Argon2d, Argon2id, scrypt, bcrypt, or PBKDF2\n - Argon2id by default")]
    pub alg: Option<String>,

    #[arg(short, long, help = "Salt, randomly generated by default")]
    pub salt: Option<String>,

    #[arg(short, long, help = "Decode salt (case insensitive)\n - Options: Base32, Base32hex, Base64\n - No decoding by default")]
    pub decode_salt: Option<String>,
}
